#!/usr/bin/env python3
"""Build offline design derivatives; --check never writes."""
import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ['DESIGN.md', 'design/tokens.json', 'design/mark.json', 'design/build.py', 'design/sync.py']


def luminance(value):
    rgb = [int(value[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    rgb = [c / 12.92 if c <= .04045 else ((c + .055) / 1.055) ** 2.4 for c in rgb]
    return sum(c * w for c, w in zip(rgb, (.2126, .7152, .0722)))


def contrast(a, b):
    a, b = sorted([luminance(a), luminance(b)])
    return (b + .05) / (a + .05)


def validate(tokens, mark):
    if not re.fullmatch(r'\d+\.\d+\.\d+', tokens['version']):
        raise ValueError('Design version must be semantic versioning')
    if tokens['core']['light'].keys() != tokens['core']['dark'].keys():
        raise ValueError('Light/dark roles differ')
    for theme in tokens['core'].values():
        for a, b in [('foreground', 'background'), ('muted-foreground', 'background'),
                     ('muted-foreground', 'card'), ('primary-foreground', 'primary')]:
            if contrast(theme[a], theme[b]) < 4.5:
                raise ValueError(f'Insufficient contrast: {a} on {b}')
    for theme in tokens['campaigns'].values():
        for role in ['text', 'muted']:
            if contrast(theme[role], theme['background']) < 4.5:
                raise ValueError(f'Insufficient campaign contrast: {role}')
    if mark['viewBox'] != '0 0 270 613' or len(mark['shapes']) != 4:
        raise ValueError('Unexpected mark dimensions or shape count')
    for shape in mark['shapes']:
        if shape['tag'] not in ['path', 'rect']:
            raise ValueError('Unsupported mark shape')
    # In the canonical repo, prove the shared geometry still matches Icon Composer.
    icon = ROOT / 'chordlist.icon/Assets/progressions.svg'
    if icon.exists():
        shapes = []
        for el in ET.fromstring(icon.read_text()).iter():
            tag = el.tag.split('}')[-1]
            if tag == 'path':
                shapes.append({'tag': tag, 'd': el.attrib['d']})
            elif tag == 'rect':
                shapes.append({'tag': tag, **{k: el.attrib[k] for k in ['x', 'y', 'width', 'height', 'rx']}})
        if shapes != mark['shapes']:
            raise ValueError('design/mark.json differs from the canonical app SVG')


def block(selector, values):
    return selector + ' {\n' + ''.join(f'  --{k}: {v};\n' for k, v in values.items()) + '}\n'


def outputs():
    tokens = json.loads((ROOT / 'design/tokens.json').read_text())
    mark = json.loads((ROOT / 'design/mark.json').read_text())
    validate(tokens, mark)
    light = {'color-scheme': 'light', **tokens['core']['light']}
    dark = {'color-scheme': 'dark', **tokens['core']['dark']}
    for theme in [light, dark]:
        theme.update({'logo-tile': tokens['brand']['tile'], 'logo-glyph': tokens['brand']['glyph'],
                      'logo-shadow': tokens['shadow']['logo'], 'radius': '0.625rem'})
        for group in ['radius', 'shadow', 'motion']:
            theme.update({f'design-{group}-{k}': v for k, v in tokens[group].items()})
    css = '/* Generated by design/build.py. Do not edit. */\n'
    css += block(':root', light) + block('.dark', dark)
    css += '@media (prefers-color-scheme: dark) {\n' + block(':root:not(.light)', dark) + '}\n'
    css = css.replace('--color-scheme:', 'color-scheme:')
    shape_markup = ''.join('<' + s['tag'] + ' ' + ' '.join(f'{k}="{html.escape(str(v), quote=True)}"'
                          for k, v in s.items() if k != 'tag') + '/>' for s in mark['shapes'])
    svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{mark["viewBox"]}" fill="currentColor" aria-hidden="true">{shape_markup}</svg>'
    generated = '// Generated by design/build.py. Do not edit.\n'
    generated += 'export const designStyles = ' + json.dumps(css) + ';\n'
    generated += 'export const designMark = ' + json.dumps(svg) + ';\n'
    manifest = {'version': tokens['version'], 'source': tokens['source'],
                'sha256': {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest() for p in SOURCES}}
    return {'design/core.css': css, 'design/mark.svg': svg + '\n', 'design/generated.ts': generated,
            'design/manifest.json': json.dumps(manifest, indent=2) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for relative, content in outputs().items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(relative)
        else:
            path.write_text(content)
    if stale:
        sys.exit('Stale design outputs: ' + ', '.join(stale) + '. Run python3 design/build.py')
    print('Design bundle checked' if args.check else 'Design bundle generated')


if __name__ == '__main__':
    main()
